/* eslint-disable @typescript-eslint/naming-convention */
const SERVICE_IDENTIFIER = {
  Warnings: Symbol.for('Warnings'),
  Errors: Symbol.for('Errors'),
  RuntimeInfo: Symbol.for('RuntimeInfo'),
  IPinoLogger: Symbol.for('IPinoLogger'),
  PinoPrettyConfiguration: Symbol.for('PinoPrettyConfiguration'),
  TLoggerFormatingConstants: Symbol.for('TLoggerFormatingConstants'),
  Server: Symbol.for('Server'),
  Client: Symbol.for('Client'),
  ErrorFactory: Symbol.for('ErrorFactory'),
  IErrorWithoutAdditionalHandling: Symbol.for('IErrorWithoutAdditionalHandling'),
  TExitCodes: Symbol.for('TExitCodes'),
  EventMessages: Symbol.for('EVENT_MESSAGES'),
  DebugInfo: Symbol.for('DebugInfo'),
  TConfiguration: Symbol.for('TConfiguration'),
  IChatService: Symbol.for('IChatService'),
  IUserService: Symbol.for('IUserService'),
  IDatabaseService: Symbol.for('IDatabaseService'),
  IPrismaService: Symbol.for('IPrismaService'),
  IUserRepository: Symbol.for('IUserRepository'),
  ISessionRepository: Symbol.for('ISessionRepository'),
  EVENT_MESSAGES: Symbol.for('EVENT_MESSAGES'),
  EXIT_CODES: Symbol.for('EXIT_CODES'),
  SIGNALS: Symbol.for('SIGNALS'),
  IPipeline: Symbol.for('IPipeline'),
  IOfflineMessageTransform: Symbol.for('IOfflineMessageTransform'),
  IMessageService: Symbol.for('IMessageService'),
  IMessageRepository: Symbol.for('IMessageRepository'),
  IChatController: Symbol.for('IChatController'),
  IServer: Symbol.for('IServer'),
}
export { SERVICE_IDENTIFIER }
